import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace

from PIL import Image

from app.assets import StillProducer, is_continuation, is_filler_narration
from app.schema import Scene, Segment, Shot, Storyboard


class ContinuationTests(unittest.TestCase):
    """Pollination: 13 of 46 shots were text cards; 9 of them only NAMED what the previous picture showed or closed the lesson."""

    def test_which_sentences_continue_the_previous_picture(self):
        for text in ["This process is known as protandry.", "This process is called homogamy.", "This structural feature is called harkogamy.",
                     "This process is termed protandry.", "Cross-pollination.", "Self-pollination.",
                     "These are also referred to as bisexual flowers."]:
            self.assertTrue(is_continuation(text), text)
        for text in ["Some flowers, such as pansies, have a hood that covers the stigma.",
                     "In flowers like orchids, the pollen from the anther does not germinate on the stigma of the same flower.",
                     "Bees visit flowers.", "The stigma receives the pollen.", ""]:
            self.assertFalse(is_continuation(text), text)

    def test_closing_lines_are_recognised(self):
        for text in ["Keep exploring to learn more.", "Keep learning.", "We believe in you."]:
            self.assertTrue(is_filler_narration(text), text)

    def _producer(self, board):
        me = StillProducer.__new__(StillProducer)
        me.board, me.issues, me._downgraded = board, [], set()
        return me

    def test_naming_and_closing_shots_reuse_the_nearest_earlier_photo(self):
        with tempfile.TemporaryDirectory() as tmp:
            photo = Path(tmp) / "a.png"
            Image.new("RGB", (64, 36), "#d9a400").save(photo)

            def seg(n, text, asset=None):
                return Segment(segment_number=n, shot_id=f"1.{n}", narration=text, visual_type="realistic_image",
                               shot=Shot(template="photo", heading="x", asset_path=asset))
            first = seg(1, "In these flowers, the anthers mature before the stigma.", str(photo))
            naming = seg(2, "This process is known as protandry.")
            specific = seg(3, "Pansies have a hood that covers the stigma, which prevents self pollination.")
            closing = seg(4, "Keep exploring to learn more.")
            board = Storyboard(title="t", scenes=[Scene(scene_number=1, title="s", narration="n", segments=[first, naming, specific, closing])])
            me = self._producer(board)
            me._plan_continuations()
            self.assertEqual([s.shot_id for _sc, s in me._continuations], ["1.2", "1.4"])      # the specific sentence is NOT a continuation
            me._apply_continuations()
            self.assertEqual(naming.shot.asset_path, str(photo))
            self.assertTrue(naming.continuation and closing.continuation)
            self.assertEqual(closing.shot.asset_path, str(photo))
            self.assertIsNone(specific.shot.asset_path)                                          # still to be generated by the normal path
            self.assertEqual([i["renderer"] for i in me.issues], ["continuation", "continuation"])

    def test_without_an_earlier_photo_it_falls_back_to_cards(self):
        only = Segment(segment_number=1, shot_id="1.1", narration="Keep learning.", visual_type="realistic_image",
                       shot=Shot(template="photo", heading="x"))
        board = Storyboard(title="t", scenes=[Scene(scene_number=1, title="s", narration="n", segments=[only])])
        me = self._producer(board)
        me.config = SimpleNamespace()
        calls = []
        me._downgrade = lambda job: calls.append(job.key) or True
        me._plan_continuations()
        me._apply_continuations()
        self.assertEqual(calls, ["1.1"])                                                        # nothing to continue from: a card as before
        self.assertFalse(only.continuation)


if __name__ == "__main__":
    unittest.main()
